<template>
  <div class="workbench-wrap">
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>
    {{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>{{this.$store.state.workbench.name}}<br>

  </div>
</template>

<script>
export default {
  name: 'workbench'
}
</script>

<style>
.workbench-wrap{
}
</style>
